import type { Metadata } from "next";
import "./globals.css";
import Header from "./_components/Templates/Header/Header";
import Sidebar from "./_components/Templates/Sidebar/Sidebar";
import { Toaster } from 'react-hot-toast'
import ThemeProvider from "./_context/ThemeContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir="rtl" lang="en">
      <body className="bg-gray-50 dark:bg-gray-900">
        <ThemeProvider>
          <Toaster />
          <div className="grid h-screen grid-cols-[300px,1fr] grid-rows-[64px,1fr]">
            {/* <div style={{ gridColumn: '2/3' , backgroundColor:'red' }}>HEADER</div>
            <div style={{ gridRow:'1/3', backgroundColor:'blue' }}>SIDEBAR</div>
            <div style={{  backgroundColor:'yellow' }}>CONTENT</div> */}
            <Header />
            <Sidebar />
            <div className="overflow-auto bg-gray-50 dark:bg-gray-900 col-span-2 lg:col-span-1" style={{}}>
              <div className="container h-full pt-8 px-4 md:px-8">
                {children}
              </div>
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
