import type { Metadata } from "next";
import "./globals.css";
import Header from "./_components/Templates/Header/Header";
import Sidebar from "./_components/Templates/Sidebar/Sidebar";
import { Toaster } from 'react-hot-toast'
import ThemeProvider from "./_context/ThemeContext";
import type { Viewport } from 'next'
import { ScrollArea } from "@/components/ui/scroll-area";
import Provider from "./Provider";


export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  // Also supported by less commonly used
  // interactiveWidget: 'resizes-visual',
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir="rtl" lang="en">
      <body className="bg-gray-50 dark:bg-gray-900">
        <Provider>
          <ThemeProvider>
            <Toaster containerStyle={{ fontFamily: 'mo' }} />
            {children}
          </ThemeProvider>
        </Provider>

      </body>
    </html>
  );
}
